# Generated by Django 5.1.5 on 2025-02-26 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('entidade', models.CharField(blank=True, default='Desconhecido', max_length=255, null=True)),
                ('nif', models.CharField(blank=True, default='Desconhecido', max_length=20, null=True)),
                ('pais', models.CharField(blank=True, default='Desconhecido', max_length=100, null=True)),
                ('data', models.DateField(blank=True, default='2024-01-01', null=True)),
                ('tipo', models.CharField(blank=True, default='Tipo Desconhecido', max_length=100, null=True)),
                ('numero_fatura', models.CharField(blank=True, default='Desconhecido', max_length=50, null=True)),
                ('iva_6', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('iva_23', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('total_iva', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('total_sem_iva', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('total_fatura', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('tipo_entidade', models.CharField(blank=True, default='Desconhecido', max_length=100, null=True)),
                ('classificacao', models.CharField(blank=True, default='Desconhecido', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_url', models.URLField(blank=True, max_length=500, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faturas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fatura_id', models.IntegerField(default='1')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
