# Generated by Django 5.1.4 on 2024-12-22 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_fatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatura',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='faturas/'),
        ),
    ]
