# Generated by Django 5.1.4 on 2024-12-26 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_fatura_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fatura',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='fatura',
            name='issue_date',
        ),
        migrations.AddField(
            model_name='fatura',
            name='data',
            field=models.DateField(default='2024-01-01'),
        ),
        migrations.AddField(
            model_name='fatura',
            name='entidade',
            field=models.CharField(default='Desconhecido', max_length=255),
        ),
        migrations.AddField(
            model_name='fatura',
            name='iva_23',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='fatura',
            name='iva_6',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='fatura',
            name='nif',
            field=models.CharField(default='Desconhecido', max_length=20),
        ),
        migrations.AddField(
            model_name='fatura',
            name='numero_fatura',
            field=models.CharField(default='Desconhecido', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='fatura',
            name='pais',
            field=models.CharField(default='Desconhecido', max_length=100),
        ),
        migrations.AddField(
            model_name='fatura',
            name='total_fatura',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='fatura',
            name='total_iva',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='fatura',
            name='total_sem_iva',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
