# Generated by Django 5.1.4 on 2024-12-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_fatura_amount_remove_fatura_issue_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fatura',
            name='numero_fatura',
            field=models.CharField(default='Desconhecido', max_length=50),
        ),
    ]
