# Generated by Django 5.1.4 on 2024-12-26 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_fatura_numero_fatura'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='fatura',
            name='data',
            field=models.DateField(blank=True, default='2024-01-01', null=True),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='entidade',
            field=models.CharField(blank=True, default='Desconhecido', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='iva_23',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='iva_6',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='nif',
            field=models.CharField(blank=True, default='Desconhecido', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='numero_fatura',
            field=models.CharField(blank=True, default='Desconhecido', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='pais',
            field=models.CharField(blank=True, default='Desconhecido', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='total_fatura',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='total_iva',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='total_sem_iva',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faturas', to=settings.AUTH_USER_MODEL),
        ),
    ]
