# Generated by Django 5.1.4 on 2025-01-03 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_fatura_data_alter_fatura_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fatura',
            name='file',
        ),
        migrations.AddField(
            model_name='fatura',
            name='file_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
