# Generated by Django 5.1.4 on 2025-01-27 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_fatura_file_fatura_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='fatura_id',
            field=models.IntegerField(default='1'),
        ),
    ]
