# Generated by Django 5.1.4 on 2025-01-27 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_note_fatura_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatura',
            name='tipo',
            field=models.CharField(blank=True, default='Tipo Desconhecido', max_length=100, null=True),
        ),
    ]
