# Generated by Django 5.1.5 on 2025-01-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_fatura_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatura',
            name='classificacao',
            field=models.CharField(blank=True, default='Desconhecido', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fatura',
            name='tipo_entidade',
            field=models.CharField(blank=True, default='Desconhecido', max_length=100, null=True),
        ),
    ]
