FROM python:3.10

# Install system dependencies (including Tesseract and Poppler)
RUN apt-get update && apt-get install -y \
    tesseract-ocr \
    tesseract-ocr-por \
    tesseract-ocr-eng \
    poppler-utils \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Copy the requirements file and install Python dependencies
COPY backend/requirements.txt .
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
RUN pip install gunicorn opencv-python-headless

# Copy the rest of the backend code
COPY backend/ .

# Use gunicorn to run the application (for production)
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "backend.wsgi:application"]
